export const TRADER_LOADING = "TRADER_LOADING";
export const TRADER_ERROR = "TRADER_ERROR";
export const TRADER_CLEAR_ERROR = "TRADER_CLEAR_ERROR";

export const TRADER_LOGIN_SUCCESS = "TRADER_LOGIN_SUCCESS";
export const TRADER_LOGOUT = "TRADER_LOGOUT";

export const TRADER_PROFILE_SUCCESS = "TRADER_PROFILE_SUCCESS";
export const TRADER_DASHBOARD_SUCCESS = "TRADER_DASHBOARD_SUCCESS";

export const QUALITY_CHECKERS_SUCCESS = "QUALITY_CHECKERS_SUCCESS";
export const CRATE_PACKERS_SUCCESS = "CRATE_PACKERS_SUCCESS";
export const TRANSPORT_OPERATORS_SUCCESS = "TRANSPORT_OPERATORS_SUCCESS";
export const CRATES_SUCCESS = "CRATES_SUCCESS";
export const REPORTS_SUCCESS = "REPORTS_SUCCESS";